# Generated by Django 4.1.7 on 2023-06-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_delete_topic_remove_post_author_remove_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='upload/'),
        ),
    ]
