# Generated by Django 4.1.7 on 2023-07-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0004_post_subtitle_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('subtitle', models.TextField(default='null')),
                ('body', models.TextField()),
                ('image', models.ImageField(default='null', upload_to='upload/')),
            ],
        ),
    ]
