# Generated by Django 4.1.7 on 2023-09-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
